def generate_runner_py(json_path, jitter_px, slow_scale, fast_scale):
    return f'''\
# Auto-generated by RuneFlow
import json, time, random
import pyautogui
from pynput import keyboard

JSON_PATH = r"{json_path}"
LOOPS = 999999
JITTER_PX = {int(jitter_px)}
SLOW_SCALE = {float(slow_scale)}
FAST_SCALE = {float(fast_scale)}

STOP = {{"flag": False}}

def _hotkey():
    def on_press(key):
        if str(key) == 'Key.esc':
            STOP["flag"] = True
            return False
    keyboard.Listener(on_press=on_press).start()

def jitter_xy(x, y, j):
    if j <= 0: return x, y
    return x + random.randint(-j, j), y + random.randint(-j, j)

def run_events(evts):
    _hotkey()
    for ev in evts:
        if STOP["flag"]: break
        delay = ev.get("delay", 0.0) * random.uniform(SLOW_SCALE, FAST_SCALE)
        time.sleep(max(0.0, delay))
        if ev["type"] == "click":
            x, y = jitter_xy(ev["x"], ev["y"], JITTER_PX)
            pyautogui.moveTo(x, y, duration=random.uniform(0.05, 0.15))
            pyautogui.click()
        elif ev["type"] == "key":
            k = ev["key"]
            if len(k) == 1: pyautogui.press(k)
            else:
                name = k.replace("Key.", "")
                pyautogui.press(name)

def main():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    evts = data["events"]
    i = 0
    while not STOP["flag"] and i < LOOPS:
        run_events(evts)
        i += 1

if __name__ == "__main__":
    time.sleep(3)  # time to focus the game
    main()
'''
